services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: taskmanager_user
      POSTGRES_PASSWORD: taskmanager_password
      POSTGRES_DB: taskmanager_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: